server:
  port: 8761

spring:
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false